locales:
  available: ["en", "vi"]
  default: "en"
users:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  show:
    gravatar:
      size: 50
  index:
    perpage: 20
  remember:
    chosen: "1"
gravatar:
  default_size: 80
micropost:
  content:
    max_length: 140
  picture:
    max_size: 5

